stages:
- build
- doc
- clean
  
debug:
  stage: build
  script:
  - make debug
  - du -h bin/debug/libtgui.so
  when: on_success
  except:
  - tags
  
release:
  stage: build
  script:
  - make release
  - du -h bin/release/libtgui.so
  when: on_success
  except:
  - tags

doc:
  stage: doc
  script:
  - make doc
  - rm -r /var/www/doc/TGUI
  - mkdir -p /var/www/doc/TGUI/downloads
  - cp -r doc/gen/html/* /var/www/doc/TGUI/
  - cp TGUI-doc.* /var/www/doc/TGUI/downloads/
  when: on_success
  artifacts:
    paths:
    - TGUI-doc.*
  except:
  - tags

clean:
  stage: clean
  script:
  - make cleandoc
  - make clean
  when: always
  except:
  - tags
