stages:
- debug
- release
- doc
- clean
  
debug:
  stage: debug
  script:
  - make debug
  - du -h bin/debug/libtgui.so
  when: on_success
  except:
  - tags
  
release:
  stage: release
  script:
  - make release
  - du -h bin/release/libtgui.so
  when: on_success
  except:
  - tags

doc:
  stage: doc
  script:
  - make doc 
  when: on_success
  artifacts:
    paths:
    - TGUI-doc.*
  except:
  - tags

clean:
  stage: clean
  script:
  - make clean
  when: always
  except:
  - tags
