stages:
- build
- doc
- clean
  
build:
  stage: build
  script:
  - ./gradlew build 
  - du -h build/libs/tgui/*/*/*
  when: on_success
  except:
  - tags

doc:
  stage: doc
  script:
  - ./gradlew doc
  - rm -r /var/www/doc/TGUI
  - mkdir -p /var/www/doc/TGUI/downloads
  - cp -r build/doc/gen/html/* /var/www/doc/TGUI/
  - cp /build/doc/TGUI-doc.* /var/www/doc/TGUI/downloads/
  when: on_success
  artifacts:
    paths:
    - /build/doc/TGUI-doc.*
  only:
  - master

clean:
  stage: clean
  script:
  - ./gradlew clean
  when: always
  except:
  - tags
