cache:
  key: "$CI_COMMIT_REF_NAME $CI_COMMIT_SHA"
  untracked: true

stages:
- build
- test
- doc
  
build:
  stage: build
  cache:
    policy: push
  script:
  - ./gradlew --console=plain assemble 
  - du -cbh build/lib/main/*/*/*
  when: on_success

checkFormatting:
  stage: test
  cache:
    policy: pull
  script:
  - ./gradlew --continue --console=plain spotlessCheck
  allow_failure: true
  when: on_success

doc:
  stage: doc
  cache:
    policy: pull
  script:
  - ./gradlew --console=plain doc
  - cp build/doc/TGUI-doc.* .
  when: on_success
  artifacts:
    paths:
    - TGUI-doc.*
